### ISSUE TITLE
emcee error

### ISSUE THREAD

**Issue by freephys** [wujian16/Cornell-MOE#37]
Without emcee, the following error shows up: 
python main.py Hartmann3 4 1
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from moe.optimal_learning.python.cpp_wrappers.log_likelihood_mcmc import GaussianProcessLogLikelihoodMCMC as cppGaussianProcessLogLikelihoodMCMC
  File "/home/ls66635/anaconda2/lib/python2.7/site-packages/moe/optimal_learning/python/cpp_wrappers/log_likelihood_mcmc.py", line 57, in <module>
    import emcee
ImportError: No module named emcee

It turns out that  emcee is imported while not in requirement.txt

import copy

import numpy
import emcee
from scipy import optimize

import moe.build.GPP as C_GP

Then I install 2.21 through pip install emcee (2.2.1)

Now another error shows up  
examples git:(master) python main.py Branin KG 4 1000 1 
emcee: Exception while calling your likelihood function:
  params: [  9.15380851e-03  -1.27299406e-01  -1.89707753e+00  -1.84206807e+01]
  args: []
  kwargs: {}
  exception:
Traceback (most recent call last):
  File "/home/ls66635/anaconda2/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "/home/ls66635/anaconda2/lib/python2.7/site-packages/moe/optimal_learning/python/cpp_wrappers/log_likelihood_mcmc.py", line 308, in compute_log_likelihood
    cpp_utils.cppify(noise),
ArgumentError: Python argument types in
    moe.build.GPP.compute_log_likelihood(list, list, int, int, LogLikelihoodTypes, list, list, int, list)
did not match C++ signature:
    compute_log_likelihood(boost::python::list, boost::python::list, int, int, optimal_learning::LogLikelihoodTypes, boost::python::list, boost::python::list)
Traceback (most recent call last):
  File "main.py", line 78, in <module>
    cpp_gp_loglikelihood.train()
  File "/home/ls66635/anaconda2/lib/python2.7/site-packages/moe/optimal_learning/python/cpp_wrappers/log_likelihood_mcmc.py", line 199, in train
    rstate0=self.rng)
  File "/home/ls66635/anaconda2/lib/python2.7/site-packages/emcee/sampler.py", line 172, in run_mcmc
    **kwargs):
  File "/home/ls66635/anaconda2/lib/python2.7/site-packages/emcee/ensemble.py", line 198, in sample
    lnprob, blobs = self._get_lnprob(p)
  File "/home/ls66635/anaconda2/lib/python2.7/site-packages/emcee/ensemble.py", line 382, in _get_lnprob
    results = list(M(self.lnprobfn, [p[i] for i in range(len(p))]))
  File "/home/ls66635/anaconda2/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "/home/ls66635/anaconda2/lib/python2.7/site-packages/moe/optimal_learning/python/cpp_wrappers/log_likelihood_mcmc.py", line 308, in compute_log_likelihood
    cpp_utils.cppify(noise),
Boost.Python.ArgumentError: Python argument types in
    moe.build.GPP.compute_log_likelihood(list, list, int, int, LogLikelihoodTypes, list, list, int, list)
did not match C++ signature:
    compute_log_likelihood(boost::python::list, boost::python::list, int, int, optimal_learning::LogLikelihoodTypes, boost::python::list, boost::python::list)

**Comment by wujian16** [comment]
Thanks for your interest. The first thing I would like to confirm is that did you clone the master branch? Because emcee is in the requirement.txt, see line 15 of https://github.com/wujian16/Cornell-MOE/blob/master/requirements.txt.

**Comment by wujian16** [comment]
I just double checked. Your error didn't show up in my case. BTW, in the error message, your c++ signature is compute_log_likelihood(boost::python::list, boost::python::list, int, int, optimal_learning::LogLikelihoodTypes, boost::python::list, boost::python::list) which didn't match that in the current master branch. Did you clone any other branch?

**Comment by zullu14** [comment]
It seems like I'm getting the same errors now, when running any function with derivatives. What's interesting is that everything works fine as long as noise array size is (1,) - so no derivative observations included. My error message: 

Traceback (most recent call last):
  File "/home/user/ENV_CMOE/lib/python3.6/site-packages/emcee/ensemble.py", line 505, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "/home/user/Cornell-MOE/moe/optimal_learning/python/cpp_wrappers/log_likelihood_mcmc.py", line 310, in compute_log_likelihood
    cpp_utils.cppify(noise),
TypeError: No registered converter was able to produce a C++ rvalue of type int from this Python object of type numpy.int64
Traceback (most recent call last):
  File "/home/user/Cornell-MOE/examples/runCMOE.py", line 315, in <module>
    main()
  File "/home/user/Cornell-MOE/examples/runCMOE.py", line 134, in main
    cpp_gp_loglikelihood.train()
  File "/home/user/Cornell-MOE/moe/optimal_learning/python/cpp_wrappers/log_likelihood_mcmc.py", line 201, in train
    rstate0=self.rng)
  File "/home/user/ENV_CMOE/lib/python3.6/site-packages/emcee/sampler.py", line 172, in run_mcmc
    **kwargs):
  File "/home/user/ENV_CMOE/lib/python3.6/site-packages/emcee/ensemble.py", line 198, in sample
    lnprob, blobs = self._get_lnprob(p)
  File "/home/user/ENV_CMOE/lib/python3.6/site-packages/emcee/ensemble.py", line 382, in _get_lnprob
    results = list(M(self.lnprobfn, [p[i] for i in range(len(p))]))
  File "/home/user/ENV_CMOE/lib/python3.6/site-packages/emcee/ensemble.py", line 505, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "/home/user/Cornell-MOE/moe/optimal_learning/python/cpp_wrappers/log_likelihood_mcmc.py", line 310, in compute_log_likelihood
    cpp_utils.cppify(noise),
TypeError: No registered converter was able to produce a C++ rvalue of type int from this Python object of type numpy.int64


The following error occurs regardless of the emcee version (tested with 2.2.1 and 2.1.0), also tested on workspace installed from source and from conda. Could you please give any information on how to run your code with derivatives and not get that error?
